# Generated by Django 5.1.5 on 2025-04-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='failed_attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='last_failed_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
