# Generated by Django 5.1.5 on 2025-04-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_accesstoken_failed_attempt_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='failed_attempt_count',
        ),
        migrations.RemoveField(
            model_name='accesstoken',
            name='last_failed_attempt',
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_failed_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
